CREATE TABLE tarefas (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
descricao VARCHAR(200),
datacriacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
dataconclusao TIMESTAMP,
concluido BOOLEAN DEFAULT false,
email VARCHAR(50),
reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);